openapi: 3.0.0
info:
  title: DISW_Price_Book API
  version: 1.0.0
paths:
  /pricebook/{recordId}:
    get:
      summary: Get DISW_Price_Book__c record by Salesforce ID
      parameters:
        - name: recordId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Record found
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Record not found
